server:
  port: 9999
  servlet:
    context-path: /
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  auto-dialect: true
  auto-runtime-dialect: true

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://106.15.61.38:3306/test01?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 12345678
      driver-class-name: com.mysql.jdbc.Driver
      max-lifetime: 1765000
      maximum-pool-size: 10
      connection-timeout: 120000
      connection-test-query: SELECT 1
logging:
  pattern:
    console:  "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
